### ISSUE TITLE
java.lang.NullPointerException is stopping the app

### ISSUE THREAD

**Issue by hcosta** [ccsoft/cordova-android-email#3]
Hello, 

I have implemented the plugin in my app and in some devices (very few) I have been getting this error. Most devices are running Android 2.3.3 - 2.3.7, and others Android 4.0.3 - 4.0.4.

I've been able to simulate the error in a device that hasn't an account configured (for example running it in a Genymotion Emulator) and capture the NullPointerException fix the problem. 

Debug info:
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=0, data=null} to activity {com.my.app/com.my.app.CordovaApp}: java.lang.NullPointerException
at android.app.ActivityThread.deliverResults(ActivityThread.java:2653)
at android.app.ActivityThread.handleSendResult(ActivityThread.java:2695)
at android.app.ActivityThread.access$2000(ActivityThread.java:157)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1031)
at android.os.Handler.dispatchMessage(Handler.java:130)
at android.os.Looper.loop(SourceFile:351)
at android.app.ActivityThread.main(ActivityThread.java:3841)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:538)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:969)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:727)
at dalvik.system.NativeStart.main(Native Method)
**Caused by: java.lang.NullPointerException
at com.ccsoft.plugin.AndroidEmail.onActivityResult(AndroidEmail.java:52)**
at org.apache.cordova.CordovaActivity.onActivityResult(CordovaActivity.java:784)
at android.app.Activity.dispatchActivityResult(Activity.java:3975)
at android.app.ActivityThread.deliverResults(ActivityThread.java:2649)
... 11 more

**Comment by koraybalci** [comment]
I added some try/catch to the mentioned block. I'd be glad if you can test and let me know.

**Comment by hcosta** [comment]
Yes it's fixed now.
Thank you.
